CONFIG_COMPANY_INFO = "company_info_config.yaml"
CONFIG_HISTORICAL = "historical_config.yaml"
CONFIG_REALTIME = "realtime_config.yaml"
CONFIG_BONDS = "bonds_config.yaml"
CONFIG_INDEX = "index_config.yaml"
CONFIG_SYMBOL_CHANGE = "symbol_change_config.yaml"

DIR_CONFIG = "config/"
DIR_CONFIG_BACKUP = "config/bak/"
DIR_OUTPUT = "output/"

OUTPUT_BONDS = "bonds_output.json"
OUTPUT_COMPANY_INFO = "company_info_output.json"
OUTPUT_HISTORICAL_COMMODITY = "historical_commodity_output.json"
OUTPUT_HISTORICAL_INDEX = "historical_index_output.json"
OUTPUT_HISTORICAL_STOCKS = "historical_stocks_output.json"
OUTPUT_REALTIME_COMMODITIES = "realtime_commodity_output.json"
OUTPUT_REALTIME_INDEX = "realtime_index_output.json"
OUTPUT_REALTIME_STOCKS = "realtime_stocks_output.json"
OUTPUT_SYMBOL_CHANGE = "symbol_change.json"
