---
- url: https://financialmodelingprep.com/api/v3/profile/{QUERY_PARAMS}?apikey={API_KEY}
  rate_limit_per_min: 300
  api_key: <PASTE KEY HERE>
  api_fields:
    symbol: _company_symbol
    price: _company_price
    beta: _company_beta
    volAvg: _company_volAvg
    mktCap: _company_mktCap
    lastDiv: _company_lastDiv
    changes: _company_changes
    companyName: _company_name
    currency: _company_currency
    cik: _company_cik
    isin: _company_isin
    cusip: _company_cusip
    exchange: _company_exchangeFullName
    exchangeShortName: _company_exchange
    industry: _company_industry
    website:
    description:
    range:
    image:
    defaultImage:
    ceo: _company_ceo
    sector: _company_sector
    country: _company_country
    fullTimeEmployees: _company_fullTimeEmployees
    phone: _company_phone
    address: _company_address
    city: _company_city
    state: _company_state
    zip: _company_zip
    dcfDiff: _company_dcfDiff
    dcf: _company_dcf
    ipoDate: _company_ipoDate
    isEtf: _company_isEtf
    isActivelyTrading: _company_isActivelyTrading
    isAdr: _company_isAdr
    isFund: _company_isFund
  non_api_fields:
    date:
    src:
    mapping: _company_date
    input_type:
    output_type:
  stocks: