---
url: https://financialmodelingprep.com/api/v3/historical-price-full/{QUERY_PARAMS}?from={START_DATE}&to={END_DATE}&apikey={API_KEY}
api_key: cae0e091a31773bcf0ffdd4bf97a9e61
rate_limit: 300
api_fields:
  symbol: _historical_symbol
  date: _historical_date
  open: _historical_open
  high: _historical_high
  low: _historical_low
  close: _historical_close
  adjClose: _historical_adjClose
  volume: _historical_volume
  unadjustedVolume: _historical_unadjustedVolume
  change: _historical_change
  changePercent: _historical_changePercent
  vwap: _historical_vwap
  changeOverTime: _historical_changeOverTime
  label: null
non_api_fields:
  name:
    src: _config_name
    mapping: _historical_name
    input_type: _string
    output_type: _string
index_composites:
 - symbol: "^GSPC"
   name: S&P 500
   start_date: 2023-11-20
   end_date: 2023-11-27
 - symbol: "^IXIC"
   name: NASDAQ Composite
   start_date: 2023-11-20
   end_date: 2023-11-27
 - symbol: "^DJI"
   name: Dow Jones Industrial Average
   start_date: 2023-11-20
   end_date: 2023-11-27
 - symbol: "^RUA"
   name: Russell 3000
   start_date: 2023-11-20
   end_date: 2023-11-27
 - symbol: "^FTSE"
   name: FTSE 100
   start_date: 2023-11-20
   end_date: 2023-11-27
stocks:

commodities:
 - symbol: HGUSD
   name: Copper
   start_date: 2023-11-20
   end_date: 2023-11-27
 - symbol: CLUSD
   name: Crude Oil
   start_date: 2023-11-20
   end_date: 2023-11-27
 - symbol: GCUSD
   name: Gold Futures
   start_date: 2023-11-20
   end_date: 2023-11-27
 - symbol: SIUSD
   name: Silver Futures
   start_date: 2023-11-20
   end_date: 2023-11-27
 - symbol: NGUSD
   name: Natural Gas
   start_date: 2023-11-20
   end_date: 2023-11-27